"""
Simulation service
=================
Exposes the AI engine's scenario definitions and executes them live against
the trained model. All perturbation math is delegated to the unchanged
``ai-engine`` ``ScenarioSimulator`` so API behaviour matches the offline
pipeline byte-for-byte.

Two modes of operation:
1. ``run_scenario()``  — runs on the training-grid sample (backwards-
   compatible default, uses ``serving.sample_grid()``).
2. ``run_current_scenario()``  — runs on the **current** feature grid
   (constructed from live OpenWeather + AQI + satellite + GIS). This is the
   architecture-correct method per the design specification.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import numpy as np
import pandas as pd

from backend.config.settings import Settings
from backend.services.live_feature_pipeline import refresh_feature_pipeline
from backend.services.scenario_cells import ScenarioCellsService
from backend.services.serving import ServingContext
from backend.utils import aie

log = logging.getLogger("backend.simulation")


def _as_gid(value) -> int | str:
    """Grid_ID is an integer in the dataset; keep it as int when possible."""
    try:
        return int(value)
    except (TypeError, ValueError):
        return value

SUMMARY_COLUMNS = [
    "scenario", "description", "baseline_lst", "mean_predicted_lst",
    "mean_delta_lst", "min_delta", "max_delta", "pct_cells_cooler",
]


class SimulationService:
    def __init__(self, settings: Settings, serving: ServingContext):
        self.settings = settings
        self.serving = serving
        self._cfg = aie.aie_config().Config()
        self.cells_service = ScenarioCellsService(settings, serving)

    # ------------------------------------------------------------------ #
    def scenarios(self) -> list[dict]:
        """The canonical scenario definitions (from ai-engine config)."""
        return [
            {
                "name": sc.name,
                "description": sc.description,
                "perturbations": {k: list(v) for k, v in sc.perturbations.items()},
            }
            for sc in self._cfg.scenarios.scenarios
        ]

    def scenario_names(self) -> list[str]:
        return [sc["name"] for sc in self.scenarios()]

    def get_scenario(self, name: str) -> dict | None:
        for sc in self.scenarios():
            if sc["name"] == name:
                return sc
        return None

    # ------------------------------------------------------------------ #
    def _simulator(self):
        return aie.aie_scenario_simulator().ScenarioSimulator(self._cfg)

    def _run_perturbation(self, X: pd.DataFrame,
                          perturbations: dict[str, tuple]) -> pd.DataFrame:
        return self._simulator()._perturb(X, perturbations)

    # ------------------------------------------------------------------ #
    def run_scenario(self, name: str) -> dict:
        """Run a named scenario on the (sampled) grid and return summary stats.

        **Backwards-compatible default**: runs on the training-grid sample,
        using ``serving.sample_grid()``. Results agree with the precomputed
        sensitivity analysis CSV generated by the offline pipeline.
        """
        sc = self.get_scenario(name)
        if sc is None:
            raise ValueError(
                f"Unknown scenario '{name}'. Available: {self.scenario_names()}"
            )
        perturbations = {k: tuple(v) for k, v in sc["perturbations"].items()}
        return self._summarize(name, sc["description"], perturbations)

    def run_current_scenario(self, name: str) -> dict:
        """Run a named scenario on the **current** feature grid.

        The baseline and perturbed predictions are computed from the live
        feature grid (constructed from OpenWeather + AQI + satellite + GIS),
        NOT from the training dataset. This is the architecture-correct method
        per the design specification.

        Returns the same summary stats as ``run_scenario()`` but based on
        current data.
        """
        sc = self.get_scenario(name)
        if sc is None:
            raise ValueError(
                f"Unknown scenario '{name}'. Available: {self.scenario_names()}"
            )
        perturbations = {k: tuple(v) for k, v in sc["perturbations"].items()}

        # Build the current feature matrix from the live feature pipeline
        X = self._build_current_feature_matrix()
        if X is None or len(X) == 0:
            raise ValueError("Current feature grid is empty - cannot run scenario")

        return self._summarize_current(name, sc["description"], perturbations, X)

    def _build_current_feature_matrix(self) -> pd.DataFrame | None:
        """Build the 58-feature matrix from the live feature pipeline.

        Returns a DataFrame with one row per grid cell, constructed by:
        1. Loading per-cell spatially-varying features from the training
           dataset (GIS, satellite, terrain — these are STATIC_GIS /
           LATEST_OBSERVATION per cell).
        2. Overriding live-updatable features (AQI) with current OpenWeather
           Air Pollution observations.
        3. Using preprocessor imputation only for genuinely missing values.

        This creates a real 53,802 × 58 matrix where each cell has its own
        feature vector, not a duplicated city-wide vector.
        """
        result = refresh_feature_pipeline(self.settings)

        # The result has feature provenance; we need per-cell data
        grid = result.get("feature_values", {})
        if not grid:
            log.warning("No feature values from live pipeline")
            return None

        pre = self.serving.preprocessor
        features_list = self.serving.features

        # --- Load per-cell spatially-varying features from the training CSV
        csv_path = Path(self.settings.dataset_csv)
        if not csv_path.exists():
            log.error("Training dataset not found: %s", csv_path)
            return None

        try:
            df = pd.read_csv(csv_path)
            log.info("Loaded training dataset: %d rows × %d cols", *df.shape)
        except Exception as exc:
            log.error("Could not load training dataset: %s", exc)
            return None

        # --- Build the feature matrix from per-cell data ---
        # Start with the training dataset's per-cell values for spatially
        # varying features.  Only override with live data where we have a
        # real current observation.

        # Identify which features to override with live data
        # These are features that have LIVE or LATEST_OBSERVATION status
        live_overrides = {}  # feature_name -> (value, source)
        for feat_name, pf_tuple in grid.items():
            if pf_tuple is None:
                continue
            # pf_tuple = (normalized_value, source, status, timestamp)
            normalized_val = pf_tuple[0] if len(pf_tuple) > 0 else None
            source = pf_tuple[1] if len(pf_tuple) > 1 else None
            status = pf_tuple[2] if len(pf_tuple) > 2 else "unavailable"
            # Only override with LIVE data (AQI) or LATEST_OBSERVATION (satellite)
            # STATIC_GIS features keep their per-cell training values
            if normalized_val is not None and status in ("LIVE", "LATEST_OBSERVATION"):
                live_overrides[feat_name] = normalized_val

        log.info(
            "Live overrides: %d features (LIVE/LATEST_OBSERVATION)",
            len(live_overrides),
        )

        # Build the matrix: per-cell values from training, with live overrides
        n_cells = len(df)
        feature_data = {}
        for feat_name in features_list:
            if feat_name in live_overrides:
                # City-wide live override (AQI, satellite mean)
                feature_data[feat_name] = [live_overrides[feat_name]] * n_cells
            elif feat_name in df.columns:
                # Per-cell spatially-varying value from training dataset
                feature_data[feat_name] = df[feat_name].values
            elif feat_name in pre.fill_values:
                # Missing feature: use preprocessor imputation
                feature_data[feat_name] = [pre.fill_values[feat_name]] * n_cells
            else:
                feature_data[feat_name] = [0.0] * n_cells

        try:
            full_grid = pd.DataFrame(feature_data, index=range(n_cells))
            # Validate: exactly 58 features, numeric, no NaN after transform
            X_full = pre.transform(full_grid[features_list])

            # Post-transform validation
            nan_count = int(X_full.isna().sum().sum())
            if nan_count > 0:
                log.warning("Post-transform NaN count: %d — filling with 0", nan_count)
                X_full = X_full.fillna(0)

            log.info(
                "Current feature matrix built: %d cells × %d features",
                len(X_full), len(features_list),
            )
            return pd.DataFrame(X_full, index=range(n_cells))
        except Exception as exc:
            log.error("Could not build current feature matrix: %s", exc)
            return None

    def get_current_grid_predictions(self) -> dict:
        """Get the full 53,802-cell current prediction grid.

        Returns a dict with:
        - predictions: list of {grid_id, predicted_lst} per cell
        - summary: mean, min, max predicted LST
        - generated_at: timestamp
        - model_version: XGBoost version
        - feature_count: 58
        """
        start = time.perf_counter()
        
        # Use the fast path from ServingContext
        result = self.serving.get_current_grid_predictions_fast()
        
        elapsed = (time.perf_counter() - start) * 1000
        log.info("Grid predictions generated in %.1f ms (cached=%s)", 
                 elapsed, result.get("cached", False))
        
        return result

    # ------------------------------------------------------------------ #
    def _summarize(self, name: str, description: str,
                   perturbations: dict[str, tuple]) -> dict:
        X = self.serving.sample_grid(self.settings.simulation_sample_size)
        baseline = np.asarray(self.serving.model.predict(X)).ravel()
        X_pert = self._run_perturbation(X, perturbations)
        perturbed = np.asarray(self.serving.model.predict(X_pert)).ravel()
        delta = perturbed - baseline

        return {
            "scenario": name,
            "description": description,
            "n_cells": len(X),
            "baseline_lst": float(np.mean(baseline)),
            "mean_predicted_lst": float(np.mean(perturbed)),
            "mean_delta_lst": float(np.mean(delta)),
            "min_delta": float(np.min(delta)),
            "max_delta": float(np.max(delta)),
            "pct_cells_cooler": float(np.mean(delta < 0) * 100.0),
            "n_perturbed_features": len(perturbations),
        }

    def _summarize_current(self, name: str, description: str,
                          perturbations: dict[str, tuple],
                          X: pd.DataFrame) -> dict:
        """Summarize a scenario run on the current feature grid."""

        baseline = np.asarray(self.serving.model.predict(X)).ravel()
        X_pert = self._run_perturbation(X, perturbations)
        perturbed = np.asarray(self.serving.model.predict(X_pert)).ravel()
        delta = perturbed - baseline

        return {
            "scenario": name,
            "description": description,
            "n_cells": len(X),
            "baseline_lst": float(np.mean(baseline)),
            "mean_predicted_lst": float(np.mean(perturbed)),
            "mean_delta_lst": float(np.mean(delta)),
            "min_delta": float(np.min(delta)),
            "max_delta": float(np.max(delta)),
            "pct_cells_cooler": float(np.mean(delta < 0) * 100.0),
            "n_perturbed_features": len(perturbations),
        }

    # ------------------------------------------------------------------ #
    def run_custom(self, perturbations: dict[str, list]) -> dict:
        """Run a caller-supplied perturbation set (validated against features)."""
        features = set(self.serving.features)
        unknown = [k for k in perturbations if k not in features]
        if unknown:
            raise ValueError(
                f"Unknown perturbation features: {unknown}. "
                f"Available features: {sorted(features)}"
            )
        cleaned = {k: (v[0], v[1]) for k, v in perturbations.items()}
        for k, (kind, _val) in cleaned.items():
            if kind not in ("add", "mul", "min", "max"):
                raise ValueError(
                    f"Invalid perturbation kind '{kind}' for '{k}' "
                    "(use add|mul|min|max)."
                )
        # Use current feature grid mode for custom perturbations too
        X = self._build_current_feature_matrix()
        if X is None or len(X) == 0:
            # Fall back to training grid if current grid unavailable
            return self._summarize("custom", "Custom perturbation set", cleaned)
        return self._summarize_current("custom", "Custom perturbation set", cleaned, X)

    # ------------------------------------------------------------------ #
    def saved_results(self) -> list[dict] | None:
        """The precomputed sensitivity analysis (pipeline output), if present."""
        path = self.settings.sensitivity_csv
        if not path.exists():
            return None
        df = pd.read_csv(path)
        return json.loads(df.to_json(orient="records"))

    # ------------------------------------------------------------------ #
    # Cell-level results (delegated to ScenarioCellsService)
    # ------------------------------------------------------------------ #
    def cells(self, name: str, refresh: bool = False) -> dict:
        """Per-cell baseline/scenario/delta results for the full grid.

        **Note**: This delegates to ``ScenarioCellsService`` which runs on the
        training grid. Use the new current-feature-grid endpoints below
        instead, or refresh the cache when live data changes.
        """
        return self.cells_service.cells(name, refresh=refresh)

    def cell_geojson(self, name: str, refresh: bool = False) -> dict:
        """WGS84 GeoJSON FeatureCollection of per-cell scenario results.

        **Note**: This delegates to ``ScenarioCellsService`` which runs on the
        training grid. For current-feature-grid results, use the new endpoints.
        """
        return self.cells_service.geojson(name, refresh=refresh)

    def regenerate_sensitivity_csv(self) -> Path:
        """Recompute the aggregate sensitivity CSV on the full grid."""
        return self.cells_service.regenerate_sensitivity_csv()

    # ------------------------------------------------------------------ #
    # New: current-feature-grid scenario endpoints
    # ------------------------------------------------------------------ #
    def run_current_scenario_cells(
        self,
        name: str,
        area_mode: str = "city",
        area_params: dict | None = None,
    ) -> dict:
        """Per-cell results for a scenario on the **current** feature grid.

        Every one of the 53,802 grid cells gets a real baseline prediction,
        a scenario-perturbed prediction and ``delta = scenario - baseline``
        computed with the trained model, **all on the current feature grid**.

        Supports area-based interventions:
        - city: Apply to entire city (default, backwards-compatible)
        - polygon: User-drawn polygon
        - neighborhood: Predefined neighborhood
        - radius: Circular area around a point
        - cells: Direct cell selection

        Returns per-cell data with provenance and area statistics.
        """
        # Ensure live data is fresh
        refresh_feature_pipeline(self.settings)

        perturbations = {}
        for sc in self._cfg.scenarios.scenarios:
            if sc.name == name:
                perturbations = {k: tuple(v) for k, v in sc.perturbations.items()}
                break

        if not perturbations:
            raise ValueError(f"Unknown scenario '{name}'. Available: {self.scenario_names()}")

        # Build current feature matrix
        X = self._build_current_feature_matrix()
        if X is None or len(X) == 0:
            raise ValueError("Current feature grid is empty - cannot compute cell results")

        # Run baseline + perturbed predictions
        perturbations_copy = dict(perturbations)
        X_pert = self._run_perturbation(X, perturbations_copy)

        baseline = np.asarray(self.serving.model.predict(X)).ravel()
        perturbed = np.asarray(self.serving.model.predict(X_pert)).ravel()
        delta = perturbed - baseline

        grid_ids = [str(gid) for gid in self.serving.grid_ids[:len(X)]]

        cells = [
            {
                "grid_id": grid_ids[i],
                "baseline_lst": float(baseline[i]),
                "scenario_lst": float(perturbed[i]),
                "delta_lst": float(delta[i]),
            }
            for i in range(len(grid_ids))
        ]

        mean_delta = float(np.mean(delta))
        pct_cooler = float(np.mean(delta < 0) * 100.0)

        return {
            "scenario": name,
            "count": len(cells),
            "cells": cells,
            "baseline_lst": float(np.mean(baseline)),
            "mean_predicted_lst": float(np.mean(perturbed)),
            "mean_delta_lst": mean_delta,
            "min_delta": float(np.min(delta)),
            "max_delta": float(np.max(delta)),
            "pct_cells_cooler": pct_cooler,
        }

    def run_current_scenario_geojson(self, name: str) -> dict:
        """MapLibre-ready GeoJSON FeatureCollection (WGS84) for a scenario on
        the current feature grid.

        Each feature's properties carry ``grid_id``, ``baseline_lst``,
        ``scenario_lst`` and ``delta_lst``; the geometry is the real grid-cell
        polygon reprojected from UTM 45N to WGS84.
        """
        data = self.run_current_scenario_cells(name)

        # Load grid geometry (shared UTM→WGS84 grid, built once)
        from backend.config.settings import Settings as SettingsCls
        from backend.services.scenario_cells import ScenarioCellsService

        settings = SettingsCls()
        cells_service = ScenarioCellsService(settings, self.serving)
        grid = cells_service._load_grid()
        geoms_key = (
            ScenarioCellsService.GEOMETRY_KEY
        )
        geoms = grid[geoms_key]

        missing = 0
        features = []
        centroids_key = ScenarioCellsService.CENTROID_KEY
        centroids = grid.get(centroids_key)

        for cell in data["cells"]:
            gid = str(cell["grid_id"])
            centroid = centroids.get(gid) if centroids else None
            if centroid is None or gid not in geoms:
                missing += 1
                continue

            ring = geoms[gid]
            cell_data = next(c for c in data["cells"] if c["grid_id"] == gid)

            features.append({
                "type": "Feature",
                "properties": {
                    "grid_id": cell_data["grid_id"],
                    "baseline_lst": cell_data["baseline_lst"],
                    "scenario_lst": cell_data["scenario_lst"],
                    "delta_lst": cell_data["delta_lst"],
                },
                "geometry": {"type": "Polygon", "coordinates": [ring]},
            })

        WGS84_CRS = {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}}

        return {
            "type": "FeatureCollection",
            "crs": WGS84_CRS,
            "features": features,
        }